### ISSUE TITLE
数学公式显示问题

### ISSUE THREAD

**Issue by amoy666** [fengdu78/Data-Science-Notes#1]
数学公式怎么才能正确显示呢？我看到是这样的
![image](https://user-images.githubusercontent.com/49981550/62106792-b58b5c00-b2d8-11e9-8160-8a872e262ff4.png)

**Comment by jiaxianhua** [comment]
<https://chrome.google.com/webstore/detail/mathjax-plugin-for-github/ioemnmodlmafdkllaclgeombjnmnbima>

部分公式可见

<img width="1021" alt="屏幕快照 2019-07-30 下午11 23 51" src="https://user-images.githubusercontent.com/315101/62142860-a1b81800-b321-11e9-989c-8f5288882ef9.png">

**Comment by amoy666** [comment]
完美的解决了我的问题，感谢大佬（*゜ー゜*）

**Comment by amoy666** [comment]
> https://chrome.google.com/webstore/detail/mathjax-plugin-for-github/ioemnmodlmafdkllaclgeombjnmnbima
> 
> 部分公式可见
> 
> <img alt="屏幕快照 2019-07-30 下午11 23 51" width="1021" src="https://user-images.githubusercontent.com/315101/62142860-a1b81800-b321-11e9-989c-8f5288882ef9.png">
