### ISSUE TITLE
CS229-LinearAlgebra 勘误

### ISSUE THREAD

**Issue by Unkrible** [fengdu78/Data-Science-Notes#3]
我们用$a^T$或者$A_{i,:}$表示矩阵$A$的第$i$行：
应更正为：
我们用$a^T_i$或者$A_{i,:}$表示矩阵$A$的第$i$行：

**Comment by Unkrible** [comment]
2.3 矩阵-矩阵乘法
矩阵乘法交换律: $(AB)C = A(BC)$
应更正为：
矩阵乘法结合律: $(AB)C = A(BC)$

**Comment by Unkrible** [comment]
3.6 线性相关性和秩
对于 $A \in \mathbb{R}^{m \times n}$,$B \in \mathbb{R}^{n \times p}$ ,$\text{rank}(A) \leq \text{min} ( \text{rank}(A), \text{rank}(B))$
应更正为
对于 $A \in \mathbb{R}^{m \times n}$,$B \in \mathbb{R}^{n \times p}$ ,$\text{rank}(AB) \leq \text{min} ( \text{rank}(A), \text{rank}(B))$

**Comment by Unkrible** [comment]
3.13 对称矩阵的特征值和特征向量
$$ x=\hat x_1u_1+\cdots +\cdots x_nu_n=U\hat x $$
数学符号未统一，应更正为
$$ x=\hat x_1u_1+\cdots +\cdots \hat x_nu_n=U\hat x $$

**Comment by fengdu78** [comment]
谢谢指导，以上已修改
