### ISSUE TITLE
CS229-Prob 勘误

### ISSUE THREAD

**Issue by Unkrible** [fengdu78/Data-Science-Notes#4]
1. 概率的基本要素
(3) $A_1,A_2,\cdots \cup_{i} A_{i} \in \mathcal{F}\Longrightarrow\cup_{i} A_{i} \in \mathcal{F}$
应更正为
(3) $A_1,A_2,\cdots A_{i} \in \mathcal{F}\Longrightarrow\cup_{i} A_{i} \in \mathcal{F}$

**Comment by fengdu78** [comment]
已经修改，谢谢
